INSERT INTO PERSON(NAME, BLOOD) VALUES ('Inchul', 'B');
INSERT INTO PERSON(NAME, BLOOD) VALUES ('Harris', 'O');

--//@UNDO

DELETE FROM PERSON WHERE (NAME = 'Inchul' AND BLOOD = 'B') OR (NAME = 'Harris' AND BLOOD = 'O');