DROP TABLE TB_BLOOD_REQ;

CREATE TABLE TB_BLOOD_REQ (
	ID VARCHAR(100) NOT NULL,
	FIRST_NAME VARCHAR(35),
	LAST_NAME VARCHAR(35),
	PHONE VARCHAR(10),
	EMAIL VARCHAR(100),
	GENDER CHAR(1), -- M for male, F for female
	BLOOD_GROUP VARCHAR(10), -- A+, A-, B+, ...
	BLOOD_VOLUME VARCHAR(2),
	REQUESTER_TYPE CHAR(1), -- C for care-giver, P for patient
	VALIDATED CHAR(1), -- Y for yes, N for no
	DATE DATETIME,
	BIRTHDAY DATE,
	STATE VARCHAR(255),
	CITY VARCHAR(255),
	HOSPITAL_ADDRESS VARCHAR(1000)
);

ALTER TABLE TB_BLOOD_REQ ADD CONSTRAINT PkBloodreq PRIMARY KEY (ID);

--//@UNDO

DROP TABLE TB_BLOOD_REQ;

CREATE TABLE TB_BLOOD_REQ (
	ID VARCHAR(13) NOT NULL,
	FIRST_NAME VARCHAR(35),
	LAST_NAME VARCHAR(35),
	PHONE VARCHAR(10),
	EMAIL VARCHAR(100),
	GENDER CHAR(1), -- M for male, F for female
	BLOOD_TYPE VARCHAR(10), -- A+, A-, B+, ...
	BLOOD_VOLUME INTEGER,
	REQUESTER_TYPE CHAR(1), -- C for care-giver, P for patient
	VALIDATED CHAR(1), -- Y for yes, N for no
	DATE DATETIME,
	BIRTHDAY DATE,
	STATE VARCHAR(1000),
	CITY VARCHAR(1000),
	HOSPITAL_ADDRESS VARCHAR(1000)
);

ALTER TABLE TB_BLOOD_REQ ADD CONSTRAINT PkBloodreq PRIMARY KEY (ID);