CREATE TABLE SUCCESS_STORY (
	ID VARCHAR(100) PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	THUMBNAIL_PATH VARCHAR(500) NOT NULL,
	VISUAL_RESOURCE_PATH VARCHAR(500) NOT NULL,
	DESCRIPTION VARCHAR(2000) NOT NULL,
	SHOW_MAIN_PAGE VARCHAR(1) NULL,
	CREATE_DATE DATE NOT NULL);

--//@UNDO

DROP TABLE SUCCESS_STORY;