INSERT INTO USER(ID, PASSWORD, FIRST_NAME, LAST_NAME, ROLE, CELL_PHONE,GENDER,BIRTH_DAY,BLOOD_GROUP,ANONYMOUS,
CITY, STATE, ADDRESS, DISTANCE, LATITUDE, LONGITUDE, LAST_DONATE_DATE, IS_ADMIN)
VALUES ('Administrator@bloodtorrent.org', 'p@ssw0rd', 'MIN', 'AD', 'ADMIN', '00000000', 'Male',
'20121212', 'A+', 'NO', 'Delhi', 'INDIA', 'BULABULA', '21', 0,0,SYSDATE ,'Y');

INSERT INTO USER(ID, PASSWORD, FIRST_NAME, LAST_NAME, ROLE, CELL_PHONE,GENDER,BIRTH_DAY,BLOOD_GROUP,ANONYMOUS,
CITY, STATE, ADDRESS, DISTANCE, LATITUDE, LONGITUDE, LAST_DONATE_DATE, IS_ADMIN)
VALUES ('inchul.hur@bloodtorrent.org', '1234', 'MIN', 'AD', 'ADMIN', '00000000', 'Male',
'20121212', 'A+', 'NO', 'Delhi', 'INDIA', 'BULABULA', '21', 0,0,SYSDATE ,'N');