UPDATE SUCCESS_STORY SET THUMBNAIL_PATH = 'ss_test01_thumb.png', VISUAL_RESOURCE_PATH = 'ss_test01.png' WHERE id='TEST01';
UPDATE SUCCESS_STORY SET THUMBNAIL_PATH = 'ss_test01_thumb.png', VISUAL_RESOURCE_PATH = 'ss_test01.png' WHERE id='TEST02';
UPDATE SUCCESS_STORY SET THUMBNAIL_PATH = 'ss_test01_thumb.png', VISUAL_RESOURCE_PATH = 'ss_test01.png' WHERE id='TEST03';
