ALTER TABLE SUCCESS_STORY ALTER COLUMN SUMMARY VARCHAR(150) NULL;
ALTER TABLE SUCCESS_STORY ALTER COLUMN VISUAL_RESOURCE_PATH VARCHAR(500) NULL;
ALTER TABLE SUCCESS_STORY ALTER COLUMN THUMBNAIL_PATH VARCHAR(500) NULL;
ALTER TABLE SUCCESS_STORY ALTER COLUMN DESCRIPTION CLOB NULL;
ALTER TABLE SUCCESS_STORY ALTER COLUMN TITLE VARCHAR(150) NOT NULL;