ALTER TABLE BLOOD_REQUEST ADD LATITUDE NUMBER NULL;
ALTER TABLE BLOOD_REQUEST ADD LONGITUDE NUMBER NULL;

--//@UNDO

ALTER TABLE BLOOD_REQUEST DROP COLUMN LATITUDE ;
ALTER TABLE BLOOD_REQUEST DROP COLUMN LONGITUDE ;
